export const AGENT_ROLES = [
  {
    id: 'planner',
    name: 'Planner',
    personality: 'Thoughtful, wide-sky thinking.',
    description: 'Understands the project, then draws a careful path forward.',
    color: '#c9b8e8',
    accent: '#8d7ab8',
    idle: 'Understanding your project',
  },
  {
    id: 'coder',
    name: 'Coder',
    personality: 'Steady hands, warm lamp light.',
    description: 'Writes in staging — never touching approved files until you say yes.',
    color: '#8ec8e6',
    accent: '#4a90b8',
    idle: 'Preparing changes',
  },
  {
    id: 'test_architect',
    name: 'Test Architect',
    personality: 'Curious, precise, a little mischievous.',
    description: 'Designs tests that catch what the happy path forgets.',
    color: '#e8c47c',
    accent: '#c9a14a',
    idle: 'Designing tests',
  },
  {
    id: 'test_executor',
    name: 'Test Executor',
    personality: 'Quiet, sandboxed, unhurried.',
    description: 'Runs the suite in an isolated world — never on your machine.',
    color: '#6a9f7a',
    accent: '#4f7a58',
    idle: 'Running sandbox',
  },
  {
    id: 'reviewer',
    name: 'Reviewer',
    personality: 'Kind, exacting, evening-window calm.',
    description: 'Reads the work as a whole and tells you what still needs love.',
    color: '#e07a5f',
    accent: '#c45d45',
    idle: 'Reviewing changes',
  },
] as const;
